name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        go: ['1.17']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Prepare checkout
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v3

    - name: Dependencies
      run: |
        go version
        go get -v -t -d ./...
        go get -u golang.org/x/lint/golint

    - name: Lint
      run: golint -set_exit_status=1 ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v -coverprofile coverage.txt -covermode atomic ./...

    - name: Coverage
      uses: codecov/codecov-action@v3
